version: 2.1
commands:
  setup-project:
    description: "Setup project"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Fetch dependencies
          command: |
            lein depsall

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

  run-tests:
    description: "Run tests"
    steps:
      - run:
          name: Run JVM tests with clojure 1.6
          command: |
            lein with-profile +1.6 test
      - run:
          name: Run JVM tests with clojure 1.7
          command: |
            lein with-profile +1.7 test
      - run:
          name: Run JVM tests with clojure 1.8
          command: |
            lein with-profile +1.8 test
      - run:
          name: Run JVM tests with clojure 1.9
          command: |
            lein with-profile +1.9 test
      - run:
          name: Run JVM tests with clojure 1.10.0
          command: |
            lein with-profile +1.10.0 test
      - run:
          name: Run JVM tests with clojure 1.10.1
          command: |
            lein with-profile +1.10.1 test

  run-reflection:
    description: "Ensure no reflection warnings"
    steps:
      - run: "! lein check 2>&1 | grep 'Reflection warning'"

jobs:
  reflection:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-node
    working_directory: ~/repo

    steps:
      - setup-project
      - run-reflection

  openjdk-8:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - setup-project
      - run-tests

  openjdk-11:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-node
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - setup-project
      - run-tests

workflows:
  version: 2
  default:
    jobs:
      - reflection
      - openjdk-8
      - openjdk-11
